version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "https://s3.console.aws.amazon.com/s3/buckets/deploy-angular-codepipeline"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes